apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-wxlcdowr
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/quay_xjiang/go-wxlcdowr:jenkins-e4cb1236eafd089d12db20de318dc8abd0d7fcac
          name: container-image
